Web:
  Address: 0.0.0.0:8080 # 监听地址
  Access-Control-Allow-Origin: "*" # 跨域访问
  Debug: true # 是否开启debug模式
  Log: true # 是否开启日志
Redis:
  Address: redis:6379 # redis地址
  Password:
  Database: 0
  TLS: false      # 是否使用TLS连接redis
  Prefix: bsz     # redis前缀
  MaxIdle: 25     # 最大空闲连接数
  MaxActive: 100  # 最大连接数
  MinIdle: 25     # 最小空闲连接数
  MaxRetries: 3   # 最大重试次数
Bsz:
  JwtSecret: "bsz" # JWT签名密钥 // 请设置为任意长度的随机值