version: "3"
services:
  redis:
    image: "redis:alpine"
    volumes:
      - ./data/redis:/data
  
  bsz:
    image: "xcsoft/busuanzi:102"
    ports:
      - "8080:8080"
    volumes:
      - ./data/dist:/app/dist
      - ./data/config:/app/config
    links:
      - redis
    depends_on:
      - redis 
    environment:
      DEBUG_ENABLE: true
      LOG_ENABLE: true
      EXPIRE_TIME: 0
      API_SERVER: https:\/\/127.0.0.1:8080\/api
