name: Docker Image CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: xcsoft
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Build Context
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: xcsoft/busuanzi:${{ github.ref_name }}

  github-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Build Context
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/soxft/busuanzi:${{ github.ref_name }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o busuanzi-linux-amd64-${{ github.ref_name }}
          GOOS=linux GOARCH=arm64 go build -o busuanzi-linux-arm64-${{ github.ref_name }}
          GOOS=darwin GOARCH=amd64 go build -o busuanzi-darwin-amd64-${{ github.ref_name }}
          GOOS=darwin GOARCH=arm64 go build -o busuanzi-darwin-arm64-${{ github.ref_name }}
          GOOS=windows GOARCH=amd64 go build -o busuanzi-windows-amd64-${{ github.ref_name }}.exe
          GOOS=windows GOARCH=arm64 go build -o busuanzi-windows-arm64-${{ github.ref_name }}.exe
          GOOS=windows GOARCH=386 go build -o busuanzi-windows-386-${{ github.ref_name }}.exe

      - name: Archive
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            busuanzi-linux-amd64-${{ github.ref_name }}
            busuanzi-linux-arm64-${{ github.ref_name }}
            busuanzi-darwin-amd64-${{ github.ref_name }}
            busuanzi-darwin-arm64-${{ github.ref_name }}
            busuanzi-windows-amd64-${{ github.ref_name }}.exe
            busuanzi-windows-arm64-${{ github.ref_name }}.exe
            busuanzi-windows-386-${{ github.ref_name }}.exe
          token: ${{ secrets.GITHUB_TOKEN }}
          release_name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: ${{ github.event.release.body }}
          draft: true