name: Docker Image CI

on:
  push:
    tags:
      - "v*.*.*"
      - "*_rc"
      - "*_beta"

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: xcsoft
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Build Context
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: xcsoft/busuanzi:${{ github.ref_name }}
      -
        # 如果不是 rc 和 beta 版本, 则推送 latest 标签
        name: Push latest tag
        if: contains(github.ref_name, 'v') && !contains(github.ref_name, 'rc') && !contains(github.ref_name, 'beta')
        run: docker tag xcsoft/busuanzi:${{ github.ref_name }} xcsoft/busuanzi:latest && docker push xcsoft/busuanzi:latest


  github-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Build Context
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/soxft/busuanzi:${{ github.ref_name }}

      - name: Push latest tag
        if: contains(github.ref_name, 'v') && !contains(github.ref_name, 'rc') && !contains(github.ref_name, 'beta')
        run: docker tag ghcr.io/soxft/busuanzi:${{ github.ref_name }} ghcr.io/soxft/busuanzi:latest && docker push ghcr.io/soxft/busuanzi:latest